x1= input("enter x1 ")
y1= input("enter y1 ")
x2= input("enter x2 ")
y2= input("enter y2 ")
x= int(x2) - int(x1)
y= int(y2) - int(y1)
step1= pow(x,2) + pow(y,2)
step2= pow(step1,0.5)
print(str(step2) + " is the distence between the 2 points")
